### ISSUE TITLE
Ver 4.0.0 Missing

### ISSUE THREAD

**Issue by bspiegel33** [kpanchen/org.openhab.binding.icomforts30#5]
I am excited to try the new version.  Thanks for making the changes.  Much appreciated.
It looks like the jar asset listed under your release of version 4.0.0 actually points to version 30-3.4.0.

**Comment by bspiegel33** [comment]
Correction - it is the new code but name says old code.  I installed and it shows the 3/24/23 version is active. 
I had to restart the binding to get it from "Resolved" to "Active".  I saw no additional channels show up.  I restarted OH and still saw no new channels.  I'll monitor performance to see how this behaves.

**Comment by kpanchen** [comment]
Fixed, sorry for that, it was just naming, code was all there.
